name: FreeBSD Tests
on:
  push:
    branches: [ "freebsd-tests" ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/*.yml'
  pull_request:
    branches: [ "freebsd-*" ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/*.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-freebsd:
    if: github.repository == 'portsbuild/elasticsearch'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      CI: false # Disabling CI for now
      RUNTIME_JAVA_HOME: /usr/local/openjdk25
      JAVA_TOOLCHAIN_HOME: /usr/local/openjdk25
      LOCAL_VEC_BINARY_OS: freebsd
      LOCAL_ZSTD_BINARY: true
      NATIVE_BUILD: local
      VEC_NATIVE_BUILD: host # future use, see ES PR #157290
      COMMON_BUILD_PARAMS: '-Dbuild.snapshot=false -Dlicense.key=px-pack/license-tools/src/test/resources/ -Drun.license_type=trial -Dorg.elasticsearch.nativeaccess.enableVectorLibrary=true -Des.nativelibs.path=/usr/local/lib'
      COMMON_TEST_PARAMS: '-Dtests.haltonfailure=false -Dnode.processors=4 -Dtests.es.node.processors=4 -Dtests.bwc.git_fetch_latest=false -Dtests.jvm.argline="--add-modules=jdk.incubator.vector --enable-native-access=ALL-UNNAMED -XX:ActiveProcessorCount=8"'
    steps:
      - uses: actions/checkout@v7

      - name: Start VM
        id: test-es-freebsd
        uses: portsbuild-vm/freebsd-vm@main
        with:
          release: "14.4"
          # arch: aarch64
          mem: 11264
          cpu: 4
          envs: 'CI RUNTIME_JAVA_HOME JAVA_TOOLCHAIN_HOME LOCAL_VEC_BINARY_OS LOCAL_ZSTD_BINARY NATIVE_BUILD COMMON_BUILD_PARAMS COMMON_TEST_PARAMS'
          copyback: false
          cache-after-prepare: true
          prepare: |
            echo "=== Install dependencies"
            mkdir -p /usr/local/etc/pkg/repos
            printf 'FreeBSD: {\n  url: "pkg+http://pkg.FreeBSD.org/${ABI}/latest"\n}\n' > /usr/local/etc/pkg/repos/FreeBSD.conf
            pkg update -f -q
            pkg install -y bash curl openjdk17 openjdk21 openjdk25 openjdk26 gmake protobuf
            echo "=== Mount procfs"
            mount -t procfs proc /proc
            java -version
            echo "=== Add dedicated action user"
            pw user add -n action -m -L root

      - name: Show runner specs
        shell: freebsd {0}
        run: |
          freebsd-version
          sysctl hw.model
          sysctl hw.ncpu
          sysctl hw.physmem
          sysctl hw.usermem
          sysctl kern.smp.cores
          sysctl kern.maxproc
          sysctl kern.maxprocperuid

      - name: Build and test
        shell: freebsd {0}
        run: |
          cd $GITHUB_WORKSPACE
          sed -i '' "s/localhost.my.domain$/localhost.my.domain $(hostname)/" /etc/hosts
          chmod +x ./.github/scripts/prepare.sh
          su action -c './.github/scripts/prepare.sh'
          chown -R action:wheel .
          mount -t procfs proc /proc
          mount -p
          echo "=== Purging sources < JDK21 && > JDK25"
          su action -c 'rm -rfv libs/entitlement/src/main27'

          echo "=== Running all tests"
          su action -c "./gradlew -S test ${COMMON_BUILD_PARAMS} ${COMMON_TEST_PARAMS}"
